[package]
name = "seqtoid-pipelines"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
seq_io = "0.3.4"
flate2 = "1.1.1"
tokio = { version= "1.44.2", features = ["rt", "sync", "process", "io-util"]}
anyhow = "1.0.97"