[package]
name = "seqtoid_pipelines"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
seq_io = "0.3.4"
flate2 = "1.1.1"
tokio = { version = "1.44.2", features = ["full", "io-util"] }
anyhow = "1.0.98"
tokio-stream = { version = "0.1.17", features = ["sync"] }
tempfile = "3.19.1"
lazy_static = "1.4.0"
rand = "0.9.1"
rand_distr = "0.5.1"
futures = "0.3.31"

[dev-dependencies]
sysinfo = "0.30"


[lib]
name = "seqtoid_pipelines"
path = "src/lib.rs"
