pub mod fastx;
pub mod file;
pub mod streams;
pub mod command;
pub mod sequence;
pub mod stats;
pub mod align;
pub mod vcf;
pub mod plotting;
pub mod sambam;
pub mod system;
pub mod paf;
pub mod blast;
mod taxonomy;
